{
    'name': 'ABS Time Off',
    'author': "TH Company",
    'summary': 'ABS Time Off',
    'category': 'AUM Business System/ Time Off',
    'website': 'https://aum.edu.vn/',
    'license': 'LGPL-3',
    'depends': [
        'base',
        'hr_holidays',
        'th_base',
        'report_docx_xlsx_in_one',
    ],
    'data': [
        'data/hr_holidays_data.xml',
        'security/time_off_security.xml',
        'security/ir.model.access.csv',
        'report/action.xml',
        'views/custom_views.xml',
        'views/popup_hr_leave.xml',
        'views/hr_leave.xml',
        'views/hr_leave_type.xml',
        'views/hr_leave_accrual_plan.xml',
        'views/hr_leave_allocation.xml',
        'wizards/batch_update_hr_leave.xml',
        'wizards/batch_update_hr_allocation.xml',
        'views/hr_holidays_views.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'assets': {
        'web.assets_backend': [
            'th_time_off/static/src/xml/calendar_filter_panel.xml',
            'th_time_off/static/src/xml/view_button_help.xml',
            'th_time_off/static/src/xml/allocation_xml/*.xml',
            'th_time_off/static/src/js/allocation_report/*.js',
            'th_time_off/static/src/js/*',
            'th_time_off/static/src/scss/*',
            'th_time_off/static/src/views/**/*',
        ],

    },
}
